#!/bin/sh

echo "auto create index in the 'README.md'"

echo "Run PreCommit.java"  

RESULT=$(java PreCommit.java 2>&1)

if [ "$RESULT" -ne 0 ]; then
        echo
        echo "Failed to run PreCommit.java"
        exit 1
fi

echo "Success to run PreCommit.java"

GIT_RESULT=$(git add ./README.md 2>&1)

if [ "$GIT_RESULT" -ne 0 ]; then
        echo
        echo "Failed to git commit updated-README.md"
        exit 1
fi

echo "Success to git commit updated-README.md"

exit 0
